.artifacts-meson: &artifacts-meson
  when: always
  paths:
   - _build/meson-logs

.meson-build: &meson-build
  - meson _build -D auto_features=enabled
  - ninja -C _build

latest-meson:
  stage: build
  image: archlinux/base:latest
  artifacts: *artifacts-meson
  before_script:
    - pacman -Syu --noconfirm --needed
        base-devel
        meson
        libdrm
        mesa
        gstreamer
        gst-plugins-base
        libpng
  script: *meson-build

oldest-meson:
  stage: build
  image: debian:stable
  artifacts: *artifacts-meson
  before_script:
    - printf > /etc/dpkg/dpkg.cfg.d/99-exclude-cruft "%s\n"
        'path-exclude=/usr/share/doc/*'
        'path-exclude=/usr/share/man/*'
    - printf > /usr/sbin/policy-rc.d "%s\n"
        '#!/bin/sh'
        'exit 101'
    - chmod +x /usr/sbin/policy-rc.d
    - apt-get update
    - apt-get -y --no-install-recommends install
        build-essential
        pkg-config
        libdrm-dev
        libgbm-dev
        libegl1-mesa-dev
        libgles2-mesa-dev
        libgstreamer1.0-dev
        libgstreamer-plugins-base1.0-dev
        gstreamer1.0-plugins-base
        gstreamer1.0-plugins-base-apps
        ninja-build
        python3 python3-pip
        libpng-dev
    - pip3 install wheel setuptools
    - pip3 install meson==0.47
  script: *meson-build

